# Gradle
org.gradle.jvmargs=-Xmx16G
org.gradle.daemon=false

# Base (Common)
mod_name=Live Player Reaction
mod_version=1.0.0
mod_group=com.mememan
mod_authors=Meme Man, LaDiamond
mod_credits=Meme Man & LaDiamond
mod_id=liveplayerreaction
mod_license=BSD 3-Clause License
mod_description=Spices Minecraft up with fluid/dynamic animations.

minecraft_version=1.20.1
mixin_plugin_version=0.7-SNAPSHOT
spongepowered_gradle_version=0.2.1-SNAPSHOT
fabric_loom_version=1.11-SNAPSHOT
legacyforge_version=2.0.107
publisher_plugin_version=0.5.2

mappings_channel_version=2023.09.03

mixin_version=0.8.5
mocha_version=3.0.0

# Base (Forge)
issue_tracker_url=https://github.com/RaveTr/LivePlayerReaction/issues
display_url=
auto_update_url=

mod_logo_path=lpr_logo.png

forge_version=47.4.6

forge_client_taskname=Live Player Reaction Forge Client
forge_server_taskname=Live Player Reaction Forge Server
forge_data_taskname=Live Player Reaction Forge DataGen

forge_mappings_channel=parchment
forge_mappings_channel_version=2023.09.03-1.20.1
forge_mappings_channel_plugin_version=1.+

forge_loader_version_range=[47,)
forge_version_range=[47,)
minecraft_version_range=[1.20.1, 1.20.2)

# Base (Fabric)
homepage_url=
source_code_url=https://github.com/RaveTr/LivePlayerReaction

mod_icon_path=lpr_logo.png

fabric_common_entrypoint=com.mememan.liveplayerreaction.LivePlayerReactionFabric
fabric_client_entrypoint=com.mememan.liveplayerreaction.LivePlayerReactionClientFabric
fabric_datagen_entrypoint=com.mememan.liveplayerreaction.LivePlayerReactionDatagenFabric

fabric_loader_version=0.16.10

fabric_client_taskname=Live Player Reaction Fabric Client
fabric_server_taskname=Live Player Reaction Fabric Server
fabric_data_taskname=Live Player Reaction Fabric DataGen

fabric_mappings_channel=parchment
fabric_mappings_channel_version=1.20.1:2023.09.03

fabric_loader_version_range=*
fabric_minecraft_version_range=1.20.1

# Dependencies (Forge) (Mandatory)
forge_playeranimator_version=1.0.2-rc1+1.20

forge_playeranimator_version_range=[1,)

# Dependencies (Fabric) (Mandatory)
fabric_api_version=0.92.2+1.20.1
fabric_playeranimator_version=1.0.2-rc1+1.20

fabric_api_version_range=>=0.91.0+1.20.1
fabric_playeranimator_version_range=>=1

# Dependencies (Forge) (Optional)
forge_jei_version=15.2.0.27
forge_jeed_version=4599236

forge_jei_version_range=[15.2.0.27,)
forge_jeed_version_range=[1.20-2.1.4,)

forge_configured_version=5180900
forge_catalogue_version=4590890
forge_gmmo_version=4658132

forge_configured_version_range=[2.2.3,)
forge_catalogue_version_range=[1.7.1,)
forge_gmmo_version_range=[2.2.1,)

forge_jade_version=4711195
forge_appleskin_version=mc1.20.1-2.5.1

forge_jade_version_range=[11.5.1,)
forge_appleskin_version_range=[mc1.20.1-2.5.1,)

# Dependencies (Fabric) (Optional)
fabric_jei_version=15.2.0.27
fabric_appleskin_version=mc1.20-2.5.1

fabric_modmenu_version=7.2.2

fabric_jei_version_range=>=15.2.0.27
fabric_appleskin_version_range=>=mc1.20-2.5.1

fabric_modmenu_version_range=>=7.2.2